name: Dependency Updates

on:
  schedule:
    - cron: '0 2 * * 1'  # Monday at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Update pip-tools
        run: |
          python -m pip install --upgrade pip pip-tools
          
      - name: Update requirements
        run: |
          pip-compile --upgrade requirements.txt || echo "pip-compile not configured yet"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: update dependencies'
          commit-message: 'chore: update dependencies'
          branch: update-dependencies
          delete-branch: true
